#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  1 18:53:10 2024

@author: lab
"""

def createScene(root_node):

   root = root_node.addChild('root', dt="0.005", gravity="0 -9 0")

   root.addObject('RequiredPlugin', name="Sofa.Component.Collision.Detection.Algorithm")
   root.addObject('RequiredPlugin', name="Sofa.Component.Collision.Detection.Intersection")
   root.addObject('RequiredPlugin', name="Sofa.Component.Collision.Response.Contact")
   root.addObject('RequiredPlugin', name="Sofa.Component.Constraint.Projective")
   root.addObject('RequiredPlugin', name="Sofa.Component.Engine.Select")
   root.addObject('RequiredPlugin', name="Sofa.Component.LinearSolver.Iterative")
   root.addObject('RequiredPlugin', name="Sofa.Component.Mass")
   root.addObject('RequiredPlugin', name="Sofa.Component.ODESolver.Backward")
   root.addObject('RequiredPlugin', name="Sofa.Component.SolidMechanics.FEM.Elastic")
   root.addObject('RequiredPlugin', name="Sofa.Component.SolidMechanics.FEM.HyperElastic")
   root.addObject('RequiredPlugin', name="Sofa.Component.StateContainer")
   root.addObject('RequiredPlugin', name="Sofa.Component.Topology.Container.Dynamic")
   root.addObject('RequiredPlugin', name="Sofa.Component.Topology.Container.Grid")
   root.addObject('RequiredPlugin', name="Sofa.Component.Topology.Mapping")
   root.addObject('RequiredPlugin', name="Sofa.Component.Visual")
   root.addObject('VisualStyle', displayFlags="showForceFields showBehaviorModels")
   root.addObject('CollisionPipeline', verbose="0")
   root.addObject('BruteForceBroadPhase', )
   root.addObject('BVHNarrowPhase', )
   root.addObject('CollisionResponse', response="PenalityContactForceField")
   root.addObject('MinProximityIntersection', name="Proximity", alarmDistance="0.8", contactDistance="0.5")
   root.addObject('DefaultAnimationLoop', )

   corrotational = root.addChild('Corrotational')
   corrotational.addObject('EulerImplicitSolver', name="cg_odesolver", printLog="false")
   corrotational.addObject('CGLinearSolver', iterations="25", name="linear solver", tolerance="1.0e-9", threshold="1.0e-9")
   corrotational.addObject('RegularGridTopology', name="hexaGrid", min="0 0 0", max="1 1 2.7", n="3 3 8", p0="0 0 0")
   corrotational.addObject('MechanicalObject', name="mechObj")
   corrotational.addObject('MeshMatrixMass', totalMass="1.0")
   corrotational.addObject('TetrahedronFEMForceField', name="FEM", youngModulus="10000", poissonRatio="0.45", method="large")
   corrotational.addObject('BoxROI', drawBoxes="0", box="0 0 0 1 1 0.05", name="box")
   corrotational.addObject('FixedConstraint', indices="@box.indices")
   corrotational.addObject('Visual3DText', text="Corrotational", position="1 0 -0.5", scale="0.2")


   ArrudaBoyce = root.addChild('ArrudaBoyce')
   ArrudaBoyce.addObject('EulerImplicitSolver', name="cg_odesolver", printLog="false")
   ArrudaBoyce.addObject('CGLinearSolver', iterations="25", name="linear solver", tolerance="1.0e-9", threshold="1.0e-9")
   ArrudaBoyce.addObject('RegularGridTopology', name="hexaGrid", min="0 0 0", max="1 1 2.7", n="3 3 8", p0="2 0 0")
   ArrudaBoyce.addObject('MechanicalObject', name="mechObj")
   ArrudaBoyce.addObject('MeshMatrixMass', totalMass="1.0")
   tetras = ArrudaBoyce.addChild('tetras')
   tetras.addObject('TetrahedronSetTopologyContainer', name="Container")
   tetras.addObject('TetrahedronSetTopologyModifier', name="Modifier")
   tetras.addObject('TetrahedronSetGeometryAlgorithms', template="Vec3", name="GeomAlgo")
   tetras.addObject('Hexa2TetraTopologicalMapping', name="default28", input="@../", output="@Container", printLog="0")
   tetras.addObject('TetrahedronHyperelasticityFEMForceField', name="FEM", ParameterSet="3448.2759 31034.483")
   ArrudaBoyce.addObject('BoxROI', drawBoxes="1", box="2 0 0 3 1 0.05", name="box")
   ArrudaBoyce.addObject('FixedConstraint', indices="@box.indices")
   ArrudaBoyce.addObject('Visual3DText', text="ArrudaBoyce", position="3 0 -0.5", scale="0.2")

   StVenantKirchhoff = root.addChild('StVenantKirchhoff')
   StVenantKirchhoff.addObject('EulerImplicitSolver', name="cg_odesolver", printLog="false")
   StVenantKirchhoff.addObject('CGLinearSolver', iterations="25", name="linear solver", tolerance="1.0e-9", threshold="1.0e-9")
   StVenantKirchhoff.addObject('RegularGridTopology', name="hexaGrid", min="0 0 0", max="1 1 2.7", n="3 3 8", p0="4 0 0")
   StVenantKirchhoff.addObject('MechanicalObject', name="mechObj")
   StVenantKirchhoff.addObject('MeshMatrixMass', totalMass="1.0")
   tetras = StVenantKirchhoff.addChild('tetras')
   tetras.addObject('TetrahedronSetTopologyContainer', name="Container")
   tetras.addObject('TetrahedronSetTopologyModifier', name="Modifier")
   tetras.addObject('TetrahedronSetGeometryAlgorithms', template="Vec3", name="GeomAlgo")
   tetras.addObject('Hexa2TetraTopologicalMapping', name="default28", input="@../", output="@Container", printLog="0")
   tetras.addObject('TetrahedronHyperelasticityFEMForceField', name="FEM", ParameterSet="3448.2759 31034.483", materialName="StVenantKirchhoff")
   StVenantKirchhoff.addObject('BoxROI', drawBoxes="1", box="4 0 0 5 1 0.05", name="box")
   StVenantKirchhoff.addObject('FixedConstraint', indices="@box.indices")
   StVenantKirchhoff.addObject('Visual3DText', text="StVenantKirchhoff", position="5 0 -0.5", scale="0.2")

   NeoHookean = root.addChild('NeoHookean')
   NeoHookean.addObject('EulerImplicitSolver', name="cg_odesolver", printLog="false")
   NeoHookean.addObject('CGLinearSolver', iterations="25", name="linear solver", tolerance="1.0e-9", threshold="1.0e-9")
   NeoHookean.addObject('RegularGridTopology', name="hexaGrid", min="0 0 0", max="1 1 2.7", n="3 3 8", p0="6 0 0")
   NeoHookean.addObject('MechanicalObject', name="mechObj")
   NeoHookean.addObject('MeshMatrixMass', totalMass="1.0")
   tetras = NeoHookean.addChild('tetras')
   tetras.addObject('TetrahedronSetTopologyContainer', name="Container")
   tetras.addObject('TetrahedronSetTopologyModifier', name="Modifier")
   tetras.addObject('TetrahedronSetGeometryAlgorithms', template="Vec3", name="GeomAlgo")
   tetras.addObject('Hexa2TetraTopologicalMapping', name="default28", input="@../", output="@Container", printLog="0")
   tetras.addObject('TetrahedronHyperelasticityFEMForceField', name="FEM", ParameterSet="3448.2759 31034.483", materialName="NeoHookean")
   NeoHookean.addObject('BoxROI', drawBoxes="1", box="6 0 0 7 1 0.05", name="box")
   NeoHookean.addObject('FixedConstraint', indices="@box.indices")
   NeoHookean.addObject('Visual3DText', text="NeoHookean", position="7 0 -0.5", scale="0.2")

   MooneyRivlin = root.addChild('MooneyRivlin')
   MooneyRivlin.addObject('EulerImplicitSolver', name="cg_odesolver", printLog="false")
   MooneyRivlin.addObject('CGLinearSolver', iterations="25", name="linear solver", tolerance="1.0e-9", threshold="1.0e-9")
   MooneyRivlin.addObject('RegularGridTopology', name="hexaGrid", min="0 0 0", max="1 1 2.7", n="3 3 8", p0="8 0 0")
   MooneyRivlin.addObject('MechanicalObject', name="mechObj")
   MooneyRivlin.addObject('MeshMatrixMass', totalMass="1.0")
   tetras = MooneyRivlin.addChild('tetras')
   tetras.addObject('TetrahedronSetTopologyContainer', name="Container")
   tetras.addObject('TetrahedronSetTopologyModifier', name="Modifier")
   tetras.addObject('TetrahedronSetGeometryAlgorithms', template="Vec3", name="GeomAlgo")
   tetras.addObject('Hexa2TetraTopologicalMapping', name="default28", input="@../", output="@Container", printLog="0")
   # tetras.addObject('TetrahedronHyperelasticityFEMForceField', name="FEM", ParameterSet="48000 152000 0.666", materialName="MooneyRivlin") #
   tetras.addObject('TetrahedronHyperelasticityFEMForceField', name="FEM", ParameterSet="3602.5 9694.5 0.1", materialName="MooneyRivlin") # C01 C10 k0 ---- C01 0.0036025 MPa C10 0.0096945 MPa
   MooneyRivlin.addObject('BoxROI', drawBoxes="1", box="8 0 0 9 1 0.05", name="box")
   MooneyRivlin.addObject('FixedConstraint', indices="@box.indices")
   MooneyRivlin.addObject('Visual3DText', text="MooneyRivlin", position="9 0 -0.5", scale="0.2")
   
   Ogden = root.addChild('Ogden')
   Ogden.addObject('EulerImplicitSolver', name="cg_odesolver", printLog="false")
   Ogden.addObject('CGLinearSolver', iterations="25", name="linear solver", tolerance="1.0e-9", threshold="1.0e-9")
   Ogden.addObject('RegularGridTopology', name="hexaGrid", min="0 0 0", max="1 1 2.7", n="3 3 8", p0="10 0 0")
   Ogden.addObject('MechanicalObject', name="mechObj")
   Ogden.addObject('MeshMatrixMass', totalMass="1.0")
   tetras = Ogden.addChild('tetras')
   tetras.addObject('TetrahedronSetTopologyContainer', name="Container")
   tetras.addObject('TetrahedronSetTopologyModifier', name="Modifier")
   tetras.addObject('TetrahedronSetGeometryAlgorithms', template="Vec3", name="GeomAlgo")
   tetras.addObject('Hexa2TetraTopologicalMapping', name="default28", input="@../", output="@Container", printLog="0")
   # tetras.addObject('TetrahedronHyperelasticityFEMForceField', name="FEM", ParameterSet="5500 1241 3.034", materialName="Ogden") # k u a -----  k = 55 kPa , u = 1.241 kPa , a = 3.034
   # tetras.addObject('TetrahedronHyperelasticityFEMForceField', name="FEM", ParameterSet="0.715 22000 1.3", materialName="Ogden") # k u a -----  k = 0.715 kPa , u = 22 kPa , a = 1.3
   tetras.addObject('TetrahedronHyperelasticityFEMForceField', name="FEM", ParameterSet="5500 1241 3.034", materialName="Ogden") # k u a -----  k = 55 kPa , u = 1.241 kPa , a = 3.034
   Ogden.addObject('BoxROI', drawBoxes="1", box="10 0 0 11 1 0.05", name="box")
   Ogden.addObject('FixedConstraint', indices="@box.indices")
   Ogden.addObject('Visual3DText', text="Ogden", position="11 0 -0.5", scale="0.2")